sudo: false
language: java

# Skip JavaDoc for CI due to issues with modules in Java 11 & 12
script: mvn verify -Droot-level="WARN" -Dmaven.javadoc.skip=true
after_success:
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash)
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk12
  - openjdk8
  - openjdk11
  - openjdk12
